modLoader="javafml"
loaderVersion="[43,)" # Forge 1.19.2の場合。43以降なら調整可
license="All Rights Reserved"
issueTrackerURL="https://your.issue.tracker.url" # 任意

[[mods]]
modId="sakaplus"
version="${file.jarVersion}"
displayName="SakaPlus"
displayURL="https://your.mod.url" # 任意
logoFile="icon.png" # 任意
credits="Created by お方"
authors="お方"
description='''
SakaPlus: Cross-loader mod using Architectury.
'''

[[dependencies.sakaplus]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.sakaplus]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.sakaplus]]
modId="architectury"
mandatory=true
versionRange="[6.5.85,)"
ordering="NONE"
side="BOTH"
