name: Generate Leafeau Item Textures

on:
  push:
    branches:
      - main3
      
jobs:
  generate_leafeau_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Download Netherite Item Textures
        run: |
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/diamond_helmet.png
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/diamond_chestplate.png
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/diamond_leggings.png
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/diamond_boots.png
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/diamond_pickaxe.png
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/diamond_sword.png
          curl -O https://raw.githubusercontent.com/Mojang/bedrock-samples/main/resource_pack/textures/items/iron_ingot.png

      - name: Prepare Output Directory
        run: mkdir -p src/main/resources/assets/sakaplus/textures/items/

      - name: Generate Leafeau Item Textures
        run: |
          COLOR="#aa3300"
          COLORIZE="75%"

          # 防具
          convert diamond_helmet.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_helmet.png
          convert diamond_chestplate.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_chestplate.png
          convert diamond_leggings.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_leggings.png
          convert diamond_boots.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_boots.png

          # ツール
          convert diamond_pickaxe.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_pickaxe.png
          convert diamond_sword.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_sword.png

          # インゴット
          convert iron_ingot.png -fill "$COLOR" -colorize $COLORIZE src/main/resources/assets/sakaplus/textures/item/pyronium_ingot.png

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add src/main/resources/assets/sakaplus/textures/item/pyronium_helmet.png \
                  src/main/resources/assets/sakaplus/textures/item/pyronium_chestplate.png \
                  src/main/resources/assets/sakaplus/textures/item/pyronium_leggings.png \
                  src/main/resources/assets/sakaplus/textures/item/pyronium_boots.png \
                  src/main/resources/assets/sakaplus/textures/item/pyronium_pickaxe.png \
                  src/main/resources/assets/sakaplus/textures/item/pyronium_sword.png \
                  src/main/resources/assets/sakaplus/textures/item/pyronium_ingot.png
          git commit -m "Generate Leafeau item textures from netherite bases" || echo "No changes to commit"
          git pull --rebase origin main3 || echo "Pull failed (likely due to conflicts or clean state)"
          git push origin HEAD:main3
