name: Find class_*** Classes

on:
  workflow_dispatch:
  push:
    branches:
      - main3

jobs:
  find-classes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo class_*** definitions from all Java files
        run: |
          for file in $(find src/main/java -type f -name '*.java'); do
            grep -E 'class\s+class_[A-Za-z0-9_]+' "$file" | while read -r line; do
              echo "$file: $line"
            done
          done
