name: Find class_*** Classes

on:
  workflow_dispatch:
  push:
    branches:
      - main3

jobs:
  find-classes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show all Java files and extract class_*** definitions
        run: |
          for file in $(find src/main/java -type f -name '*.java'); do
            echo "==== $file ===="
            cat "$file"
            grep -E 'class\s+class_[A-Za-z0-9_]+' "$file" | while read -r line; do
              echo "[class_*** found] $line"
            done
          done
