name: Find class_*** Classes

on:
  workflow_dispatch:
  push:
    branches:
      - main3

jobs:
  find-classes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Find all Java files and output class_*** definitions
        run: |
          find src/main/java -type f -name '*.java'
          while IFS= read -r file; do
            grep -E 'class\s+class_[A-Za-z0-9_]+' "$file" && echo "==== $file ====";
          done < filelist.txt
