name: Replace ModEntities with ModEntities3

on:
  workflow_dispatch:
  push:
    branches:
      - main3

jobs:
  replace-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace ModEntities with ModEntities3 in .java files
        run: |
          find . -type f -name '*.java' -exec sed -i 's/ModEntities33/ModEntities3/g' {} +

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Replace ModEntities with ModEntities3 in .java files via GitHub Actions"
            git pull --rebase origin main3 || echo "Pull failed (likely due to conflicts or clean state)"
            git push origin HEAD:main3
          else
            echo "No changes to commit."
          fi
