name: Decompile jar with FernFlower and arrange sources

on:
  push:
    branches:
      - main3
  workflow_dispatch:

jobs:
  decompile-and-arrange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main3 branch
        uses: actions/checkout@v4
        with:
          ref: main3

      - name: Download v1.1.4 jar
        run: |
          curl -L -o Itemplus-1.0.0.jar "https://github.com/Konnitiwa768/Itemplus/releases/download/v1.1.4/Itemplus-1.0.0.jar"

      - name: Extract all contents from jar
        run: |
          mkdir extracted
          cd extracted
          jar xf ../Itemplus-1.0.0.jar
          cd ..

      - name: Download FernFlower
        run: |
          curl -L -o fernflower.jar https://github.com/JetBrains/intellij-community/raw/master/plugins/java-decompiler/engine/fernflower.jar

      - name: Decompile class files with FernFlower
        run: |
          mkdir -p decompiled
          # FernFlowerはjarに対して直接実行できるが、classファイルディレクトリでもOK
          java -jar fernflower.jar -rbr=0 -dgs=1 extracted/ decompiled/

      - name: Move decompiled .java sources to src/main/java
        run: |
          # fernflowerは元のパッケージ構造で.javaを吐くので、そのままsrc/main/javaに移動
          find decompiled -name "*.java" | while read file; do
            relpath=$(echo "$file" | sed 's@^decompiled/@@')
            mkdir -p "src/main/java/$(dirname "$relpath")"
            mv "$file" "src/main/java/$relpath"
          done

      - name: Move resources to proper places
        run: |
          # META-INF → ルート直下
          if [ -d extracted/META-INF ]; then
            rm -rf META-INF
            mv extracted/META-INF .
          fi
          # assets → src/main/resources/assets
          if [ -d extracted/assets ]; then
            rm -rf src/main/resources/assets
            mkdir -p src/main/resources
            mv extracted/assets src/main/resources/
          fi
          # fabric.mod.json → src/main/resources/
          if [ -f extracted/fabric.mod.json ]; then
            mv extracted/fabric.mod.json src/main/resources/
          fi
          # fabric → src/main/resources/
          if [ -d extracted/fabric ]; then
            rm -rf src/main/resources/fabric
            mv extracted/fabric src/main/resources/
          fi

      - name: Commit and force push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add META-INF src/main/java src/main/resources/assets src/main/resources/fabric src/main/resources/fabric.mod.json || true
          git diff --cached --quiet || git commit -m "Decompiled .java sources and restored resources from v1.1.4 jar"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main3
