name: Extract all from v1.1.4 jar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main3

      - name: Download v1.1.4 jar (check for success)
        run: |
          set -e
          curl -L -o Itemplus-1.0.0.jar "https://github.com/Konnitiwa768/Itemplus/releases/download/v1.1.4/Itemplus-1.0.0.jar"
          file Itemplus-1.0.0.jar
          # HTMLならエラーとして終了
          if file Itemplus-1.0.0.jar | grep -q HTML; then
            echo "Downloaded file is not a jar. Check the URL or release file existence."
            exit 1
          fi

      - name: Try unzip, fallback to jar xf
        run: |
          # まずunzipを試す
          mkdir -p extracted_v1.1.4
          if unzip -o Itemplus-1.0.0.jar -d extracted_v1.1.4; then
            echo "Unzip succeeded."
          else
            echo "Unzip failed, trying 'jar xf'..."
            cd extracted_v1.1.4
            jar xf ../Itemplus-1.0.0.jar
            cd ..
          fi

      - name: Commit and force push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add extracted_v1.1.4
          git diff --cached --quiet || git commit -m "Extract all files from v1.1.4 jar"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main3
