name: Decompile .class files with Procyon (keep directory structure)

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Procyon Decompiler
        run: |
          curl -L -o procyon-decompiler.jar https://repo1.maven.org/maven2/org/bitbucket/mstrobel/procyon-decompiler/0.6.0/procyon-decompiler-0.6.0.jar
          ls -lh procyon-decompiler.jar
          file procyon-decompiler.jar

      - name: Decompile all .class files (keep directory structure)
        run: |
          mkdir -p decompiled/src/main/java
          find src/main/java -type f -name "*.class" | while read classfile; do
            relative_path="${classfile#src/main/java/}"
            output_dir="decompiled/src/main/java/$(dirname "$relative_path")"
            mkdir -p "$output_dir"
            java -jar procyon-decompiler.jar "$classfile" -o "$output_dir"
          done

      - name: Commit and push decompiled files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add decompiled
          git commit -m "Decompiled .class files with Procyon (directory structure preserved)" || echo "No changes to commit"
          git push
