name: Decompile Classes with Bytecode Viewer (Krakatau only)

on:
  push:
    branches: [main3]
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (main3)
        uses: actions/checkout@v3
        with:
          ref: main3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download Bytecode Viewer (with decompilers)
        run: |
          curl -L -o Bytecode-Viewer.jar https://github.com/Konloch/bytecode-viewer/releases/latest/download/Bytecode-Viewer.jar

      - name: Decompile classes from classlist.txt with Krakatau only
        run: |
          while IFS= read -r classpath; do
            if [ -f "$classpath" ]; then
              dir=$(dirname "$classpath")
              base=$(basename "$classpath" .class)
              java -jar Bytecode-Viewer.jar -import "$classpath" -decompile Krakatau -output "$dir/${base}.java" || true
            fi
          done < classlist.txt

      - name: Commit and push decompiled sources
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Decompiled classes from classlist.txt with Bytecode Viewer (Krakatau)"
          git push
