name: Create main2 Branch at Specific Commit

on:
  workflow_dispatch:  # 手動実行

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no specific ref)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴を取得して特定のコミットを扱えるようにする

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create main2 branch at target commit
        run: |
          git fetch origin
          git checkout -b main3 4e8ddcfa371449c43ca731b63fc4aced32b0b448
          git push origin main3
