name: Decompile .class files with Procyon (in-place to src/main/java)

on:
  push:
    branches:
      - main3
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Procyon Decompiler
        run: |
          curl -L -o procyon-decompiler.jar https://github.com/mstrobel/procyon/releases/download/v0.6.0/procyon-decompiler-0.6.0.jar

      - name: Decompile all .class files to src/main/java (NO decompiled/, NO path loop)
        run: |
          find src/main/java -type f -name "*.class" > classlist.txt
          if [ -s classlist.txt ]; then
            java -jar procyon-decompiler.jar @classlist.txt -o src/main/java
          fi

      - name: Commit and push decompiled files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Decompiled .class files with Procyon (in-place .java, cleaned paths)" || echo "No changes to commit"
          git pull --rebase origin main3 || echo "Nothing to rebase"
          git push
