name: Generate Gemstone Recipes

on:
  push:
    branches:
      - main

jobs:
  generate_gemstone_recipes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare Output Directory
        run: mkdir -p src/main/resources/data/sakaplus/recipes

      - name: Generate Recipe JSONs without EOF
        run: |
          echo '{' > src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '  "type": "minecraft:crafting_shapeless",' >> src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '  "ingredients": [' >> src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '    { "item": "minecraft:lapis_lazuli" },' >> src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '    { "item": "minecraft:diamond" }' >> src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '  ],' >> src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '  "result": { "item": "sakaplus:gemstone", "count": 4 }' >> src/main/resources/data/sakaplus/recipes/gemstone.json
          echo '}' >> src/main/resources/data/sakaplus/recipes/gemstone.json

          for item in helmet chestplate leggings boots pickaxe sword; do
            echo '{' > src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            echo '  "type": "minecraft:crafting_shaped",' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json

            if [ "$item" = "helmet" ]; then
              echo '  "pattern": ["XXX", "X X"],' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            elif [ "$item" = "chestplate" ]; then
              echo '  "pattern": ["X X", "XXX", "XXX"],' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            elif [ "$item" = "leggings" ]; then
              echo '  "pattern": ["XXX", "X X", "X X"],' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            elif [ "$item" = "boots" ]; then
              echo '  "pattern": ["X X", "X X"],' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            elif [ "$item" = "pickaxe" ]; then
              echo '  "pattern": ["XXX", " # ", " # "],' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            elif [ "$item" = "sword" ]; then
              echo '  "pattern": ["X", "X", "#"],' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            fi

            echo '  "key": {' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            echo '    "X": { "item": "sakaplus:gemstone" },' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json

            if [ "$item" = "pickaxe" ] || [ "$item" = "sword" ]; then
              echo '    "#": { "item": "minecraft:stick" }' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            fi

            echo '  },' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            echo '  "result": { "item": "sakaplus:gemstone_'${item}'" }' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
            echo '}' >> src/main/resources/data/sakaplus/recipes/gemstone_${item}.json
          done

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}

          git add src/main/resources/data/sakaplus/recipes/*.json
          git commit -m "Generate Gemstone recipes (no EOF)" || echo "No changes to commit"
          git pull --rebase origin main || echo "Pull failed (possibly clean state)"
          git push origin HEAD:main
