name: Deobfuscate and Upload to Release

on:
  push:
    branches:
      - main3
  workflow_dispatch:

jobs:
  deobfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. JARダウンロード（curl使用）
      - name: Download Obfuscated JAR (curl)
        run: |
          curl -L -o itemplus-1.0.0.jar "https://github.com/Konnitiwa768/Itemplus/releases/download/v1.1.4/Itemplus-1.0.0.jar"

      # 2. Enigma CLIダウンロード（curl使用）
      - name: Download Enigma CLI (curl)
        run: |
          curl -L -o enigma-cli.jar "https://github.com/FabricMC/Enigma/releases/latest/download/enigma-cli.jar"

      # 3. Yarnマッピングダウンロード（curl使用、1.19.2+build.28）
      - name: Download Yarn mappings (curl)
        run: |
          curl -L -o mappings.tiny "https://github.com/FabricMC/yarn/releases/download/1.19.2+build.28/mappings.tiny"

      # 4. Enigmaでデオブフスケート
      - name: Deobfuscate JAR using Enigma
        run: |
          java -jar enigma-cli.jar \
            --mappings mappings.tiny \
            --input itemplus-1.0.0.jar \
            --output itemplus-1.0.0-deobf.jar \
            --from obf \
            --to named

      # 5. リリースへアップロード
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.5
          files: itemplus-1.0.0-deobf.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
